package com.pd.pdp.server.mapper;

import com.pd.pdp.server.entity.LoginLogEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface LoginLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_login_log
     *
     * @mbggenerated Fri Oct 16 15:32:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_login_log
     *
     * @mbggenerated Fri Oct 16 15:32:45 CST 2020
     */
    int insert(LoginLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_login_log
     *
     * @mbggenerated Fri Oct 16 15:32:45 CST 2020
     */
    int insertSelective(LoginLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_login_log
     *
     * @mbggenerated Fri Oct 16 15:32:45 CST 2020
     */
    LoginLogEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_login_log
     *
     * @mbggenerated Fri Oct 16 15:32:45 CST 2020
     */
    int updateByPrimaryKeySelective(LoginLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_login_log
     *
     * @mbggenerated Fri Oct 16 15:32:45 CST 2020
     */
    int updateByPrimaryKey(LoginLogEntity record);

    List<LoginLogEntity> selectLoginLogList();
}