package com.pd.pdp.server.mapper;

import com.pd.pdp.server.entity.UserRoleEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UserRoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insert(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insertSelective(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    UserRoleEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKeySelective(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKey(UserRoleEntity record);

    /**
     * @Author pdp
     * @Description 检查角色是否绑定权限
     * @Param [ids]
     * @return int
     **/
    int checkRoleByRoleIds(List<String> ids);

    /**
     * @Author pdp
     * @Description 删除用户角色
     * @Param [userId]
     * @return int
     **/
    int deleteByUserId(Integer userId);


    int deleteAllByUserId(@Param("ids") List<String> ids);
}