package com.pd.pdp.server.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: au_dict_type
 */
@Data
public class DictTypeEntity implements Serializable {
    /**
     * 主键
     *
     * Table:     au_dict_type
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 类型编码
     *
     * Table:     au_dict_type
     * Column:    code
     * Nullable:  false
     */
    private String code;

    /**
     * 类型名称
     *
     * Table:     au_dict_type
     * Column:    name
     * Nullable:  false
     */
    private String name;

    /**
     * 描述信息
     *
     * Table:     au_dict_type
     * Column:    description
     * Nullable:  true
     */
    private String description;

    /**
     * 字典类型状态：0-可用，1-不可用，2-删除
     *
     * Table:     au_dict_type
     * Column:    status
     * Nullable:  false
     */
    private Integer status;

    /**
     * 创建信息的用户id
     *
     * Table:     au_dict_type
     * Column:    create_user_id
     * Nullable:  true
     */
    private Integer createUserId;

    /**
     * 创建的时间
     *
     * Table:     au_dict_type
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 更新信息的用户id
     *
     * Table:     au_dict_type
     * Column:    update_user_id
     * Nullable:  true
     */
    private Integer updateUserId;

    /**
     * 更新的时间
     *
     * Table:     au_dict_type
     * Column:    update_time
     * Nullable:  true
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_dict_type
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}