package com.pd.pdp.server.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Id;
import java.util.Date;

/**
 * Table: mysql_hive_schema_check
 */
@Data
@ApiModel("角色实体类对象")
public class MysqlHiveSchemaCheck {
    /**
     * 主键
     *
     * Table:     mysql_hive_schema_check
     * Column:    id
     * Nullable:  false
     */
    @Id
    @Column(name = "id")
    @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     * 系统名称
     *
     * Table:     mysql_hive_schema_check
     * Column:    system_name
     * Nullable:  false
     */
    @ApiModelProperty(value = "系统名称")
    private String systemName;

    /**
     * 数据库名称
     *
     * Table:     mysql_hive_schema_check
     * Column:    db_name
     * Nullable:  false
     */
    @ApiModelProperty(value = "数据库名称")
    private String dbName;

    /**
     * 数据库表名称
     *
     * Table:     mysql_hive_schema_check
     * Column:    table_name
     * Nullable:  false
     */
    @ApiModelProperty(value = "数据库表名称")
    private String tableName;

    /**
     * source连接
     *
     * Table:     mysql_hive_schema_check
     * Column:    url
     * Nullable:  true
     */
    @ApiModelProperty(value = "url")
    private String url;

    /**
     * 数据库表添加的字段
     *
     * Table:     mysql_hive_schema_check
     * Column:    source_add_cloumns
     * Nullable:  true
     */
    @ApiModelProperty(value = "数据库表添加的字段")
    private String sourceAddCloumns;

    /**
     * 数据库表删除的字段
     *
     * Table:     mysql_hive_schema_check
     * Column:    source_delete_cloumns
     * Nullable:  true
     */
    @ApiModelProperty(value = "url")
    private String sourceDeleteCloumns;

    /**
     * 创建人名称
     *
     * Table:     mysql_hive_schema_check
     * Column:    create_user
     * Nullable:  true
     */
    @ApiModelProperty(value = "创建人名称")
    private String createUser;

    /**
     * 编辑人名称
     *
     * Table:     mysql_hive_schema_check
     * Column:    update_user
     * Nullable:  true
     */
    @ApiModelProperty(value = "编辑人名称")
    private String updateUser;

    /**
     * 创建时间
     *
     * Table:     mysql_hive_schema_check
     * Column:    create_time
     * Nullable:  false
     */
    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    /**
     * 系统时间
     *
     * Table:     mysql_hive_schema_check
     * Column:    update_time
     * Nullable:  true
     */
    @ApiModelProperty(value = "系统时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}
