package com.pd.pdp.server.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

/**
 * Table: platform_info
 */
@Data
@ApiModel("角色实体类对象")
public class PlatformInfo implements Serializable {
    /**
     * 主键
     *
     * Table:     platform_info
     * Column:    id
     * Nullable:  false
     */
    @Id
    @Column(name = "id")
    @ApiModelProperty(value = "平台ID")
    private Integer id;

    /**
     * 平台名称
     *
     * Table:     platform_info
     * Column:    name
     * Nullable:  false
     */
    @ApiModelProperty(value = "平台名称")
    private String name;

    /**
     * 平台url
     *
     * Table:     platform_info
     * Column:    url
     * Nullable:  false
     */
    @ApiModelProperty(value = "平台url")
    private String url;

    /**
     * 平台url类型
     *
     * Table:     platform_info
     * Column:    url_type
     * Nullable:  false
     */
    @ApiModelProperty(value = "平台url类型")
    private Integer urlType;

    /**
     * url优先级
     *
     * Table:     platform_info
     * Column:    url_sort
     * Nullable:  false
     */
    @ApiModelProperty(value = "url优先级")
    private Integer urlSort;

    /**
     * 创建人ID
     *
     * Table:     platform_info
     * Column:    create_user_id
     * Nullable:  true
     */
    @ApiModelProperty(value = "创建人ID")
    private Integer createUserId;

    /**
     * 编辑人ID
     *
     * Table:     platform_info
     * Column:    update_user_id
     * Nullable:  true
     */
    @ApiModelProperty(value = "编辑人ID")
    private Integer updateUserId;

    /**
     * 创建时间
     *
     * Table:     platform_info
     * Column:    create_time
     * Nullable:  false
     */
    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    /**
     * 系统时间
     *
     * Table:     platform_info
     * Column:    update_time
     * Nullable:  true
     */
    @ApiModelProperty(value = "系统时间")
    private Date updateTime;

    /**
     * 状态：0-不可用，1-可用，2-删除
     *
     * Table:     platform_info
     * Column:    status
     * Nullable:  false
     */
    @ApiModelProperty(value = "状态：0-不可用，1-可用，2-删除")
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}