package com.pd.pdp.server.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: au_role_auth
 */
@Data
public class RoleAuthEntity implements Serializable {
    /**
     * Table:     au_role_auth
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 角色id
     *
     * Table:     au_role_auth
     * Column:    role_id
     * Nullable:  false
     */
    private Integer roleId;

    /**
     * 权限id
     *
     * Table:     au_role_auth
     * Column:    auth_id
     * Nullable:  false
     */
    private Integer authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_role_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}