package com.pd.pdp.server.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: au_sys
 */
@Data
public class SysEntity implements Serializable {
    /**
     * 主键
     *
     * Table:     au_sys
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 系统名称
     *
     * Table:     au_sys
     * Column:    name
     * Nullable:  false
     */
    private String name;

    /**
     * 系统代号
     *
     * Table:     au_sys
     * Column:    code
     * Nullable:  true
     */
    private String code;

    /**
     * 描述信息
     *
     * Table:     au_sys
     * Column:    description
     * Nullable:  true
     */
    private String description;

    /**
     * 创建信息的用户id
     *
     * Table:     au_sys
     * Column:    create_user_id
     * Nullable:  true
     */
    private Integer createUserId;

    /**
     * 创建的时间
     *
     * Table:     au_sys
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 更新信息的用户
     *
     * Table:     au_sys
     * Column:    update_user_id
     * Nullable:  true
     */
    private Integer updateUserId;

    /**
     * 更新的时间
     *
     * Table:     au_sys
     * Column:    update_time
     * Nullable:  true
     */
    private Date updateTime;

    /**
     * 状态：0-不可用，1-可用，2-删除
     *
     * Table:     au_sys
     * Column:    status
     * Nullable:  true
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_sys
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}