# 开发环境配置
server:
  servlet:
    context-path:

spring:
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

  ### xxl-job, email
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    from: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          starttls:
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    url: jdbc:mysql://localhost:3306/pdp_db?serverTimezone=GMT%2B8
    username: root
    password: pdroot21
    driver-class-name: com.mysql.jdbc.Driver
  ## 集成Redis
  redis:
    ## Redis服务器连接地址
    host: pd-cdh-192-168-0-10-node
    ## Redis服务器连接端口
    port: 6379
    timeout: 5000
    ## Redis服务器连接密码（默认为空）
    password: foobared
    ## Redis服务器连接db
    database: 2
    ## 连接超时时间（毫秒）
    lettuce:
      pool:
        ## 连接池中的最大连接数
        max-idle: 8
        ## 连接池中的最小连接数
        min-idle: 0
        ## 连接池中的最大空闲连接
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

#  actuator 配置将所有端口暴露，如不配置只有/health和/info俩个端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      enabled: true
  endpoint:
    health:
      showDetails: always
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pd.pdp.mapper
  configuration:
    map-underscore-to-camel-case: true

### xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
xxl:
  job:
    i18n: zh_CN
    ## xxl-job, triggerpool max size
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    ### xxl-job, access token
    accessToken:
    ### xxl-job, log retention days
    logretentiondays: 30