spring:
  # 应用名称
  application:
    name: pdp
    # 配置文件
  profiles:
    active: dev
    # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  logging: debug
# 应用服务 WEB 访问端口
server:
    port: 8084
