package com.pd.pdp.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: au_auth
 */
@Data
public class AuthEntity implements Serializable {
    /**
     * 主键
     *
     * Table:     au_auth
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 系统id
     *
     * Table:     au_auth
     * Column:    sys_id
     * Nullable:  false
     */
    private Integer sysId;

    /**
     * 权限名称
     *
     * Table:     au_auth
     * Column:    name
     * Nullable:  false
     */
    private String name;

    /**
     * 权限状态:0-不可用，1-可用，2-删除
     *
     * Table:     au_auth
     * Column:    status
     * Nullable:  false
     */
    private Integer status;

    /**
     * 权限类型:1-菜单，2-按钮，3-权限
     *
     * Table:     au_auth
     * Column:    type
     * Nullable:  false
     */
    private Integer type;

    /**
     * 权限url
     *
     * Table:     au_auth
     * Column:    url
     * Nullable:  true
     */
    private String url;

    /**
     * 权限标识
     *
     * Table:     au_auth
     * Column:    auth_key
     * Nullable:  false
     */
    private String authKey;

    /**
     * 排列序号
     *
     * Table:     au_auth
     * Column:    sort_no
     * Nullable:  false
     */
    private Integer sortNo;

    /**
     * 父权限id
     *
     * Table:     au_auth
     * Column:    parent_id
     * Nullable:  true
     */
    private Integer parentId;

    /**
     * 权限样式
     *
     * Table:     au_auth
     * Column:    clazz
     * Nullable:  true
     */
    private String clazz;

    /**
     * 跳转目标页面名称
     *
     * Table:     au_auth
     * Column:    target
     * Nullable:  true
     */
    private String target;

    /**
     * 描述信息
     *
     * Table:     au_auth
     * Column:    description
     * Nullable:  true
     */
    private String description;

    /**
     * 创建信息的用户id
     *
     * Table:     au_auth
     * Column:    create_user_id
     * Nullable:  true
     */
    private Integer createUserId;

    /**
     * 创建时间
     *
     * Table:     au_auth
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 更新用户
     *
     * Table:     au_auth
     * Column:    update_user_id
     * Nullable:  true
     */
    private Integer updateUserId;

    /**
     * 更新时间
     *
     * Table:     au_auth
     * Column:    update_time
     * Nullable:  true
     */
    private Date updateTime;
    
    /**
     * @Author pdp
     * @Description 父权限名称
     * @Date 5:08 下午 2020/10/22
     * @Param 
     * @return 
     **/
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}