package com.pd.pdp.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * Table: au_login_log
 */
@Data
@ApiModel("用户实体类对象")
public class LoginLogEntity implements Serializable {
    /**
     * 主键
     *
     * Table:     au_login_log
     * Column:    id
     * Nullable:  false
     */
    @ApiModelProperty(notes = "登陆日志ID")
    private Integer id;

    /**
     * 用户主键id
     *
     * Table:     au_login_log
     * Column:    user_id
     * Nullable:  false
     */
    @ApiModelProperty(notes = "用户ID")
    private Integer userId;

    /**
     * 用户名
     *
     * Table:     au_login_log
     * Column:    user_name
     * Nullable:  true
     */
    @ApiModelProperty(notes = "用户名")
    private String userName;

    /**
     * 系统主键id
     *
     * Table:     au_login_log
     * Column:    sys_id
     * Nullable:  true
     */
    @ApiModelProperty(notes = "系统主键ID")
    private Integer sysId;

    /**
     * 登录地址
     *
     * Table:     au_login_log
     * Column:    ip
     * Nullable:  true
     */
    @ApiModelProperty(notes = "登录地址")
    private String ip;

    /**
     * 登录平台:1-PC,2-Android,3-iPhone,4-微信
     *
     * Table:     au_login_log
     * Column:    platform
     * Nullable:  true
     */
    @ApiModelProperty(notes = "登录平台:1-PC,2-Android,3-iPhone,4-微信")
    private Integer platform;

    /**
     * 登录时间
     *
     * Table:     au_login_log
     * Column:    time
     * Nullable:  true
     */
    @ApiModelProperty(notes = "登录时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date time;

    /**
     * 描述信息
     *
     * Table:     au_login_log
     * Column:    description
     * Nullable:  true
     */
    @ApiModelProperty(notes = "描述信息")
    private String description;

    /**
     * 是否在线
     */
    @ApiModelProperty(notes = "是否在线")
    private String isLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_login_log
     *
     * @mbggenerated Fri Oct 16 15:32:45 CST 2020
     */
    private static final long serialVersionUID = 1L;
}