package com.pd.pdp.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

/**
 * Table: au_oper_log
 */
@Data
public class OperLogEntity implements Serializable {
    /**
     * 主键
     *
     * Table:     au_oper_log
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 用户主键id
     *
     * Table:     au_oper_log
     * Column:    user_id
     * Nullable:  false
     */
    private Integer userId;

    /**
     * 操作类型
     *
     * Table:     au_oper_log
     * Column:    type
     * Nullable:  true
     */
    private String type;

    /**
     * 操作时间
     *
     * Table:     au_oper_log
     * Column:    time
     * Nullable:  false
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date time;

    /**
     * 描述信息
     *
     * Table:     au_oper_log
     * Column:    description
     * Nullable:  true
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_oper_log
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}