package com.pd.pdp.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: au_user_role
 */
@Data
public class UserRoleEntity implements Serializable {
    /**
     * 主键
     *
     * Table:     au_user_role
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 员工主键id
     *
     * Table:     au_user_role
     * Column:    user_id
     * Nullable:  false
     */
    private Integer userId;

    /**
     * 角色主键id
     *
     * Table:     au_user_role
     * Column:    role_id
     * Nullable:  false
     */
    private Integer roleId;

    /**
     * 分配人id
     *
     * Table:     au_user_role
     * Column:    create_user_id
     * Nullable:  true
     */
    private Integer createUserId;

    /**
     * 分配时间
     *
     * Table:     au_user_role
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_user_role
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}