package com.pd.pdp.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * Table: au_user
 */
@Data
@ApiModel("用户实体类对象")
public class UserEntity implements Serializable {
    /**
     * 主键
     *
     * Table:     au_user
     * Column:    id
     * Nullable:  false
     */
    @ApiModelProperty(notes = "用户ID")
    private Integer id;

    /**
     * 用户真实姓名
     *
     * Table:     au_user
     * Column:    user_name
     * Nullable:  true
     */
    @ApiModelProperty(notes = "用户名")
    private String userName;

    /**
     * 账号
     *
     * Table:     au_user
     * Column:    account
     * Nullable:  false
     */
    @ApiModelProperty(notes = "账号")
    private String account;

    /**
     * 手机号
     *
     * Table:     au_user
     * Column:    phone
     * Nullable:  false
     */
    @ApiModelProperty(notes = "手机号")
    private String phone;

    /**
     * 密码
     *
     * Table:     au_user
     * Column:    password
     * Nullable:  false
     */
    @ApiModelProperty(notes = "密码", hidden = true)
    private String password;

    /**
     * 状态：0-不可用，1-可用，2-删除
     *
     * Table:     au_user
     * Column:    status
     * Nullable:  false
     */
    @ApiModelProperty(notes = "状态: 0-不可用，1-可用，2-删除")
    private Integer status;

    /**
     * 组织id
     *
     * Table:     au_user
     * Column:    org_id
     * Nullable:  true
     */
    @ApiModelProperty(notes = "组织ID")
    private Integer orgId;

    /**
     * 组织类别
     *
     * Table:     au_user
     * Column:    org_type
     * Nullable:  true
     */
    @ApiModelProperty(notes = "组织类型")
    private Integer orgType;

    /**
     * 描述信息
     *
     * Table:     au_user
     * Column:    description
     * Nullable:  true
     */
    @ApiModelProperty(notes = "描述")
    private String description;

    /**
     * 创建信息的用户id
     *
     * Table:     au_user
     * Column:    create_user_id
     * Nullable:  true
     */
    @ApiModelProperty(notes = "创建人ID")
    private Integer createUserId;

    /**
     * 创建的时间
     *
     * Table:     au_user
     * Column:    create_time
     * Nullable:  true
     */
    @ApiModelProperty(notes = "创建时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     * 更新信息的用户id
     *
     * Table:     au_user
     * Column:    update_user_id
     * Nullable:  true
     */
    @ApiModelProperty(notes = "更新人ID")
    private Integer updateUserId;

    /**
     * 更新的时间
     *
     * Table:     au_user
     * Column:    update_time
     * Nullable:  true
     */
    @ApiModelProperty(notes = "更新时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * 角色ID
     */
    @ApiModelProperty(notes = "角色ID", hidden = true)
    private Integer roleId;

    /**
     * 角色名称
     */
    @ApiModelProperty(notes = "角色名称")
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_user
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
}