package com.pd.pdp.mapper;

import com.pd.pdp.entity.DictTypeEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface DictTypeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict_type
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict_type
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insert(DictTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict_type
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insertSelective(DictTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict_type
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    DictTypeEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict_type
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKeySelective(DictTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict_type
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKey(DictTypeEntity record);
}