package com.pd.pdp.mapper;

import com.pd.pdp.entity.DictEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface DictEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insert(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insertSelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    DictEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKeySelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_dict
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKey(DictEntity record);
}