package com.pd.pdp.mapper;

import com.pd.pdp.entity.OperLogEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface OperLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_oper_log
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_oper_log
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insert(OperLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_oper_log
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insertSelective(OperLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_oper_log
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    OperLogEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_oper_log
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKeySelective(OperLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_oper_log
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKey(OperLogEntity record);
}