package com.pd.pdp.mapper;

import com.pd.pdp.entity.RoleAuthEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RoleAuthEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_role_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_role_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insert(RoleAuthEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_role_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insertSelective(RoleAuthEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_role_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    RoleAuthEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_role_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKeySelective(RoleAuthEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_role_auth
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKey(RoleAuthEntity record);

    /**
     * @Author pdp
     * @Description 根据角色查询权限
     * @Date 10:30 下午 2020/10/17
     * @Param [roleId]
     * @return java.util.List<java.lang.Integer>
     **/
    List<Integer> selectAllAuthIdByRoleId(Integer roleId);

    /**
     * @Author pdp
     * @Description 
     * @Date 10:11 上午 2020/10/18
     * @Param [ids]
     * @return int
     **/
    int checkAuthByAuthIds(List<String> ids);
}