package com.pd.pdp.mapper;

import com.pd.pdp.entity.SysEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SysEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_sys
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_sys
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insert(SysEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_sys
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int insertSelective(SysEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_sys
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    SysEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_sys
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKeySelective(SysEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_sys
     *
     * @mbggenerated Thu Oct 15 13:19:35 CST 2020
     */
    int updateByPrimaryKey(SysEntity record);
}